name: ubuntu

on:
  push:
    branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]
    paths:
      - 'Dockerfile.ubuntu'
      - '.github/workflows/docker-ubuntu.yml'
      - '.github/workflows/docker-common.yml'
      - 'docker-bake.hcl'
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths:
      - 'Dockerfile.ubuntu'
      - '.github/workflows/docker-ubuntu.yml'
      - '.github/workflows/docker-common.yml'
      - 'docker-bake.hcl'
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/docker-common.yml
    with:
      dockerfile: Dockerfile.ubuntu
      bake_target: ubuntu-based
      cache_scope: ubuntu
      image-suffixes: ubuntu,scientific