name: Docker Full Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-full.yml'
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-full.yml'
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      image-suffix: full
      dockerfile: Dockerfile
      target: full
      cache-scope: full