name: Docker CTANFull Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile.full'
      - 'Dockerfile.basic'
      - '.github/workflows/docker-ctanfull.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile.full'
      - 'Dockerfile.basic'
      - '.github/workflows/docker-ctanfull.yml'

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      image-suffix: ctanfull
      dockerfile: Dockerfile.full
      version: ${{ github.ref_name }}
      cache-scope: ctanfull
      needs-basic: true