name: ubuntu

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
    paths:
      - 'Dockerfile.ubuntu'
      - '.github/workflows/docker-ubuntu.yml'
      - '.github/workflows/docker-common.yml'
      - 'docker-bake.hcl'
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths:
      - 'Dockerfile.ubuntu'
      - '.github/workflows/docker-ubuntu.yml'
      - '.github/workflows/docker-common.yml'
      - 'docker-bake.hcl'
  release:
    types: [published]

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    uses: ./.github/workflows/docker-common.yml
    with:
      dockerfile: Dockerfile.ubuntu
      bake_target: ubuntu-based
      cache_scope: ubuntu
      image_ref: ghcr.io/mbogochow/latex:ubuntu