name: Docker CTANBasic Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-ctanbasic.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-ctanbasic.yml'

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      image-suffix: ctanbasic
      dockerfile: Dockerfile
      target: base
      version: ${{ github.ref_name }}
      cache-scope: ctanbasic
