name: alpine

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-alpine.yml'
      - '.github/workflows/docker-common.yml'
      - 'docker-bake.hcl'
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-alpine.yml'
      - '.github/workflows/docker-common.yml'
      - 'docker-bake.hcl'
  release:
    types: [published]

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    uses: ./.github/workflows/docker-common.yml
    with:
      dockerfile: Dockerfile
      bake_target: alpine
      cache_scope: alpine
      image_ref: ghcr.io/mbogochow/latex:minimal