name: Docker Ubuntu Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
    paths:
      - 'Dockerfile.ubuntu'
      - '.github/workflows/docker-ubuntu.yml'
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths:
      - 'Dockerfile.ubuntu'
      - '.github/workflows/docker-ubuntu.yml'
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      image-suffix: ubuntu
      dockerfile: Dockerfile.ubuntu
      target: texlive-full
      cache-scope: ubuntu
