name: Docker Ubuntu Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile.ubuntu'
      - '.github/workflows/docker-ubuntu.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile.ubuntu'
      - '.github/workflows/docker-ubuntu.yml'

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      image-suffix: ubuntu
      dockerfile: Dockerfile.ubuntu
      version: ${{ github.ref_name }}
      cache-scope: ubuntu
      needs-basic: false