name: common

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
        description: "Name of the Dockerfile to build"
      bake_target:
        required: true
        type: string
        description: "Target to build in docker-bake.hcl"
      cache_scope:
        required: true
        type: string
        description: "Scope for build cache"
      image-suffixes:
        required: true
        type: string
        description: "Comma-separated list of image tag suffixes (e.g. 'minimal,full' or 'ubuntu,ubuntu-full')"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mbogochow/latex

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # Only run on PR if it was merged
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # This step generates Docker image tags based on different GitHub events:
    # - For releases (tags): Base tag + tag version (e.g., ghcr.io/mbogochow/latex:minimal-v1.0.0)
    # - For pushes to main: Tag with 'dev' and commit SHA (e.g., ghcr.io/mbogochow/latex:minimal-dev)
    # - For PRs: Tag with 'dev' and PR number (e.g., ghcr.io/mbogochow/latex:minimal-pr-123)
    # These tags are later passed to docker/bake-action to tag all built images
    - name: Generate tag rules
      id: tags
      run: |
        declare -A target_tags_array
        image="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        IFS=',' read -ra suffixes <<< "${{ inputs.image-suffixes }}"

        # Initialize arrays for each suffix
        for suffix in "${suffixes[@]}"; do
          target_tags_array[$suffix]=""
        done

        # Collect all tags based on context
        for suffix in "${suffixes[@]}"; do
          base_tag="${image}:${suffix}"

          # For tags (releases)
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            # For releases, include both base tag and version tag
            target_tags_array[$suffix]+="$base_tag "
            target_tags_array[$suffix]+="${base_tag}-${{ github.ref_name }} "
          fi

          # For pushes to main
          if [[ "${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}" == "true" ]]; then
            # For main branch, only use dev and SHA tags
            target_tags_array[$suffix]+="${base_tag}-dev "
            target_tags_array[$suffix]+="${base_tag}-${{ github.sha }} "
          fi

          # For pull requests
          if [[ "${{ github.event_name == 'pull_request' }}" == "true" ]]; then
            # For PRs, only use dev and PR number tags
            target_tags_array[$suffix]+="${base_tag}-dev "
            target_tags_array[$suffix]+="${base_tag}-pr-${{ github.event.pull_request.number }} "
          fi
        done

        # Generate tag overrides with separate entries for each tag
        tag_overrides=""
        for suffix in "${suffixes[@]}"; do
          # Read space-separated tags into an array
          read -ra tags <<< "${target_tags_array[$suffix]}"

          # Add each tag as a separate override
          for tag in "${tags[@]}"; do
            if [[ -n "$tag" ]]; then
              if [[ -n "$tag_overrides" ]]; then
                tag_overrides="${tag_overrides}\n"
              fi
              # Format: target_name.tags=tag (no quotes)
              tag_overrides="${tag_overrides}${suffix}.tags=${tag}"
            fi
          done
        done

        echo "tag_overrides<<EOF" >> $GITHUB_OUTPUT
        echo -e "$tag_overrides" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Build and push Docker images
      id: build-and-push
      uses: docker/bake-action@v6
      with:
        files: |
          ./docker-bake.hcl
        targets: ${{ inputs.bake_target }}
        push: true
        set: |
          *.cache-from=type=gha,scope=${{ inputs.cache_scope }}
          *.cache-to=type=gha,mode=max,scope=${{ inputs.cache_scope }}
          *.output=type=registry
          *.args.CI=true
          ${{ steps.tags.outputs.tag_overrides }}

    # TODO: need to debug failures
    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: ${{ inputs.image_ref }}
    #     format: 'table'
    #     exit-code: '1'
    #     ignore-unfixed: true
    #     vuln-type: 'os,library'
    #     severity: 'CRITICAL,HIGH'